source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MsaUIKitExtensions_Example', :exclusive => true do
  pod 'MsaUIKitExtensions', :path => '../'
end

target 'MsaUIKitExtensions_Tests', :exclusive => true do
  pod 'MsaUIKitExtensions', :path => '../'

  pod 'FBSnapshotTestCase'
end
